[pytest]
# Путь для сохранения allure результатов
addopts =
    --alluredir=allure-results
    -v

# Маркеры для организации тестов
markers =
    smoke: Быстрые тесты для проверки основного функционала
    positive: Позитивные сценарии
    negative: Негативные сценарии